// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBT27BOJt7alb7VcxniBnjkNqy_x3i-9Q',
    appId: '1:180778005523:web:06e9c851d32b82b6d2fbe6',
    messagingSenderId: '180778005523',
    projectId: 'quidvy-62ro',
    authDomain: 'quidvy-62ro.firebaseapp.com',
    storageBucket: 'quidvy-62ro.appspot.com',
    measurementId: 'G-TVRK9CH3JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2zKl9TjmC0e9KmZI_DGp3uZRYrILinFc',
    appId: '1:180778005523:android:d301df8516011620d2fbe6',
    messagingSenderId: '180778005523',
    projectId: 'quidvy-62ro',
    storageBucket: 'quidvy-62ro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI_St4ZCPtxy5SxORKg3l_8VusSESwaOU',
    appId: '1:180778005523:ios:046f26e837185a14d2fbe6',
    messagingSenderId: '180778005523',
    projectId: 'quidvy-62ro',
    storageBucket: 'quidvy-62ro.appspot.com',
    iosBundleId: 'com.example.quidvy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI_St4ZCPtxy5SxORKg3l_8VusSESwaOU',
    appId: '1:180778005523:ios:da24f38f7c137581d2fbe6',
    messagingSenderId: '180778005523',
    projectId: 'quidvy-62ro',
    storageBucket: 'quidvy-62ro.appspot.com',
    iosBundleId: 'com.example.quidvy.RunnerTests',
  );
}
